name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: Release version
        required: true
        type: string
      notes:
        description: Release notes
        required: true
        type: string

env:
  VERSION: ${{ inputs.version }}
  NOTES: ${{ inputs.notes }}

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create $VERSION --notes "$NOTES"

  build:
    runs-on: ubuntu-latest
    needs: release
    strategy:
      matrix:
        # go tool dist list
        dist: [darwin/amd64, darwin/arm64, linux/amd64, windows/amd64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Build
        shell: bash
        env:
          DIST: ${{ matrix.dist }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          export GOOS=$(echo $DIST | cut -d '/' -f 1)
          export GOARCH=$(echo $DIST | cut -d '/' -f 2)
          ZIP=$GOOS-$GOARCH-$VERSION.zip
          go build -o fbp -ldflags "-X main.Version=$VERSION" cmd/fbp/main.go
          zip -r $ZIP fbp examples
          gh release upload $VERSION $ZIP
